2021-05-13 09:20:35,183 INFO    MainThread:3694 [wandb_setup.py:_flush():69] setting env: {}
2021-05-13 09:20:35,183 INFO    MainThread:3694 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-13 09:20:35,183 INFO    MainThread:3694 [wandb_init.py:_log_setup():336] Logging user logs to /home/hsyang/workspace/20210306_gan/GAN_with_diversity/wandb/run-20210513_092035-3gfkgd12/logs/debug.log
2021-05-13 09:20:35,184 INFO    MainThread:3694 [wandb_init.py:_log_setup():337] Logging internal logs to /home/hsyang/workspace/20210306_gan/GAN_with_diversity/wandb/run-20210513_092035-3gfkgd12/logs/debug-internal.log
2021-05-13 09:20:35,184 INFO    MainThread:3694 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f21758cdee0>
2021-05-13 09:20:35,185 INFO    MainThread:3694 [wandb_init.py:init():369] calling init triggers
2021-05-13 09:20:35,185 INFO    MainThread:3694 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-13 09:20:35,185 INFO    MainThread:3694 [wandb_init.py:init():418] starting backend
2021-05-13 09:20:35,185 INFO    MainThread:3694 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-13 09:20:35,343 INFO    MainThread:3694 [backend.py:ensure_launched():123] starting backend process...
2021-05-13 09:20:35,483 INFO    MainThread:3694 [backend.py:ensure_launched():127] started backend process with pid: 16271
2021-05-13 09:20:35,484 INFO    MainThread:3694 [wandb_init.py:init():423] backend started and connected
2021-05-13 09:20:35,503 INFO    MainThread:3694 [wandb_init.py:init():465] updated telemetry
2021-05-13 09:20:35,504 INFO    MainThread:3694 [wandb_init.py:init():484] communicating current version
2021-05-13 09:20:36,442 INFO    MainThread:3694 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.30 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-13 09:20:36,444 INFO    MainThread:3694 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-13 09:20:36,727 INFO    MainThread:3694 [wandb_init.py:init():522] starting run threads in backend
2021-05-13 09:20:37,336 INFO    MainThread:3694 [wandb_run.py:_console_start():1554] atexit reg
2021-05-13 09:20:37,337 INFO    MainThread:3694 [wandb_run.py:_redirect():1401] redirect: SettingsConsole.WRAP
2021-05-13 09:20:37,337 INFO    MainThread:3694 [wandb_run.py:_redirect():1444] Wrapping output streams.
2021-05-13 09:20:37,337 INFO    MainThread:3694 [wandb_run.py:_redirect():1468] Redirects installed.
2021-05-13 09:20:37,337 INFO    MainThread:3694 [wandb_init.py:init():546] run started, returning control to user process
2021-05-13 09:20:37,341 INFO    MainThread:3694 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-13 09:20:37,341 INFO    MainThread:3694 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-13 09:25:10,459 INFO    MainThread:3694 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-13 09:26:03,241 INFO    MainThread:3694 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-13 09:26:03,241 INFO    MainThread:3694 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-13 09:27:27,231 INFO    MainThread:3694 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-13 09:27:29,892 INFO    MainThread:3694 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-13 09:27:29,892 INFO    MainThread:3694 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-13 09:27:36,294 INFO    MainThread:3694 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-13 09:27:48,360 INFO    MainThread:3694 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-13 09:27:48,360 INFO    MainThread:3694 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-13 09:28:49,476 INFO    MainThread:3694 [wandb_run.py:_atexit_cleanup():1524] got exitcode: 0
2021-05-13 09:28:49,477 INFO    MainThread:3694 [wandb_run.py:_restore():1496] restore
2021-05-13 09:28:49,744 INFO    MainThread:3694 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 815
  total_bytes: 815
}

2021-05-13 09:28:50,241 INFO    MainThread:3694 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3056
  total_bytes: 3056
}

2021-05-13 09:28:50,343 INFO    MainThread:3694 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3056
  total_bytes: 3056
}

2021-05-13 09:28:50,445 INFO    MainThread:3694 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3056
  total_bytes: 3056
}

2021-05-13 09:28:50,547 INFO    MainThread:3694 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3056
  total_bytes: 3056
}

2021-05-13 09:28:50,650 INFO    MainThread:3694 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3056
  total_bytes: 3056
}

2021-05-13 09:28:50,752 INFO    MainThread:3694 [wandb_run.py:_wait_for_finish():1646] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3056
  total_bytes: 3056
}

2021-05-13 09:28:51,868 INFO    MainThread:3694 [wandb_run.py:_show_files():1868] logging synced files
